# QUESTION 1

In [1]:
import numpy as np
arr = np.arange(2,51,3).tolist()
print(arr)

[2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50]


# QUESTION 2

In [2]:
list1 = []
print("Enter Elements for List 1 :-")
for i in range(0,5):
    x = int(input())
    list1.append(x)


list2 = []
print("Enter Elements for List 2 :-")
for f in range(0,5):
    y = int(input())
    list2.append(y)
print("Two Lists Entered are :-")
print(list1)
print(list2)
print("")
import numpy as np
np1 = np.array(list1)
np2 = np.array(list2)
print("Two Arrays are :-")
print(np1)
print(np2)
print("")
con = np.concatenate((np1,np2))
print("Concatenated Array is :-")
print(con)
print("")
sort = np.sort(con)
print("Sorted Array is :-")
print(sort)

Enter Elements for List 1 :-
1
2
3
4
5
Enter Elements for List 2 :-
6
7
8
9
0
Two Lists Entered are :-
[1, 2, 3, 4, 5]
[6, 7, 8, 9, 0]

Two Arrays are :-
[1 2 3 4 5]
[6 7 8 9 0]

Concatenated Array is :-
[1 2 3 4 5 6 7 8 9 0]

Sorted Array is :-
[0 1 2 3 4 5 6 7 8 9]


# QUESTION 3

In [3]:
import numpy as np
arr1 = np.array([[14,15,16],[20,21,23],[4,5,6]])
print(arr1)
print("")
print("The dimension of above array is :  " + str(arr1.ndim))
print("")
print("The size of above string is :   " + str(arr1.size))

[[14 15 16]
 [20 21 23]
 [ 4  5  6]]

The dimension of above array is :  2

The size of above string is :   9


# QUESTION 4

In [4]:
import numpy as np
arr2 = np.random.rand(2,)
print(arr2.ndim)
arr3 = arr2[np.newaxis , :]
print(arr3.ndim)

1
2


# QUESTION 5

In [7]:
import numpy as np
arr1 = np.random.rand(2,3)
arr2 = np.random.rand(2,3)
print(np.vstack((arr1,arr2)))
print()
print(np.hstack((arr1,arr2)))

[[0.47279985 0.14735601 0.92935914]
 [0.61708628 0.40913327 0.56136535]
 [0.12861314 0.99093084 0.68499525]
 [0.06709407 0.06363105 0.3992365 ]]

[[0.47279985 0.14735601 0.92935914 0.12861314 0.99093084 0.68499525]
 [0.61708628 0.40913327 0.56136535 0.06709407 0.06363105 0.3992365 ]]


# QUESTION 6

In [8]:
import numpy as np
arr = np.array([1,2,5,8,6,1,5,3,5,7,9,4,6,2,4,8,5,1,3,6,2])
print(np.unique(arr, return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([3, 3, 2, 2, 4, 3, 1, 2, 1], dtype=int64))
